language: python
sudo: false
python:
{%- for version in cookiecutter.setup_info.python_versions %}
  - "{{ version }}"
{%- endfor %}
install:
  - pip install tox
  - pip install tox-travis
  - pip install python-coveralls
script: tox
after_success:
  - coveralls
